//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorDetail
    {
        public int VisitorId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Company { get; set; }
        public string Visiting { get; set; }
        public string Idtype { get; set; }
        public string Idnum { get; set; }
        public string Vnumber { get; set; }
        public string Contactno { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public System.DateTime ctime { get; set; }
    }
}
